#ifndef PRESSIOLOG_VERSION_HPP
#define PRESSIOLOG_VERSION_HPP

#define PRESSIOLOG_MAJOR_VERSION 0
#define PRESSIOLOG_MINOR_VERSION 15
#define PRESSIOLOG_PATCH_VERSION 0

#endif // PRESSIOLOG_VERSION_HPP