name: github-Linux-baseline

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths-ignore:
    - 'scripts/**'
  push:
    branches:
      - 'main'
    paths-ignore:
    - 'scripts/**'

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  CI:
    name: baseline
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        image:
          - fedora-clang-17
          - fedora-gnu-13
          - ubuntu-clang-14
          - ubuntu-gnu-11
        build_type:
          - Release
          - Debug
        cmake_extra_args:
          - ''
          - '-D PRESSIO_ENABLE_TPL_MPI=ON'
        include:
          - image: ubuntu-clang-14
            build_type: Release
            cmake_extra_args: '-D CMAKE_CXX_STANDARD=20'

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pressio/${{ matrix.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    env:
      num_cpus: 3

    steps:
      - uses: actions/checkout@v4

      - name: Install MPI
        if: contains(matrix.cmake_extra_args, 'PRESSIO_ENABLE_TPL_MPI')
        run: |
          apt-get update && apt-get install -y mpich libmpich-dev

      - name: Configure
        run: |
            cmake -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} ${{ matrix.cmake_extra_args }}

      - name: Build
        run: |
          cmake --build build --target install

      - name: Run tests
        working-directory: build/tests/logging
        run: |
          ctest -j $num_cpus --output-on-failure
