name: github-Linux-baseline

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths-ignore:
    - 'scripts/**'
  push:
    branches:
      - 'main'
    paths-ignore:
    - 'scripts/**'

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  CI:
    name: baseline
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        image:
          - fedora-clang-mpi-17
          - fedora-gnu-mpi-13
        cmake_extra_args:
          - ''
          - '-D PRESSIO_ENABLE_TPL_MPI=ON'

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pressio/${{ matrix.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    env:
      num_cpus: 3
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          echo "localhost slots=$num_cpus" | tee -a /usr/lib64/openmpi-default-hostfile

      - name: Configure
        run: |
          cmake -B build \
                -D CMAKE_BUILD_TYPE=Debug \
                -D CMAKE_PREFIX_PATH=/usr/lib64 \
                -D CMAKE_CXX_FLAGS="-Werror" \
                ${{ matrix.cmake_extra_args }}

      - name: Build
        run: |
          cmake --build build --target install

      - name: Run tests
        working-directory: build/tests/logging
        run: |
          ctest -j $num_cpus --output-on-failure
